install:
  - cinst: "7zip"
  - ps: get-command "7z.*"
  - ps: write-host "installing sublime text 3"
  - ps: start-filedownload "http://c758482.r82.cf2.rackcdn.com/Sublime Text Buidl 3062 x64.zip"
  - ps: get-childitem
  - ps: write-host "installing UnitTesting"

build: false

test_script:
  - ps: C:\projects\apptest\app.ps1
